### ISSUE TITLE
JWT token expires in 1 hour

### ISSUE THREAD

**Issue by mirceaiscoding** [mirceaiscoding/netflix-recommendations#13]
I decoded a token on https://jwt.io and saw that it expires in 1 hour.

Should we change the tokens so that they don't expire?
And will this be secure?

**Comment by StefanGrigorescu** [comment]
[https://gist.github.com/soulmachine/b368ce7292ddd7f91c15accccc02b8df](url)
I found this on the token expiration topic. It mentions the recommended approaches for web apps too.

**Comment by StefanGrigorescu** [comment]
[https://code-maze.com/using-refresh-tokens-in-asp-net-core-authentication/](url)     - a very useful documentation I checked to implement the refresh token system. The site approaches the frontend part too!
