### ISSUE TITLE
OrderBy Utility functions (BE)

### ISSUE THREAD

**Issue by StefanGrigorescu** [mirceaiscoding/netflix-recommendations#16]
Create Utility functions for OrderBy LINQ method in order to manipulate the output depending on what filter parameters are passed in the request url.

It mitght be useful to implement them as Extension Methods; see:    [https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods](url)

**Comment by mirceaiscoding** [comment]
We could also add an optional limit to the number of given results
