### ISSUE TITLE
Unit Of Work

### ISSUE THREAD

**Issue by StefanGrigorescu** [mirceaiscoding/netflix-recommendations#5]
One feature needs to apply an atomic set of modifications to the database (only one transaction).

[https://www.c-sharpcorner.com/UploadFile/b1df45/unit-of-work-in-repository-pattern/](url)   - concept presented

Is the AddScoped service enough to provide the unit of work characteristics?

**Comment by StefanGrigorescu** [comment]
[https://stackoverflow.com/questions/58601276/change-services-addscopedunitofwork-to-services-addtransient-because-of](url)

[https://stackoverflow.com/questions/41058142/injecting-dbcontext-into-service-layer](url)       - it is enough to use services with scoped LifeTime for a single transaction within a request

**Comment by mirceaiscoding** [comment]
It was decided to use scoped. To be reopened if this changes

**Comment by mirceaiscoding** [comment]
It was decided to use scoped. To be reopened if this changes
